# HyperStreamDB: Full Pipeline Presentation

**Version:** 0.1.9 (Alpha)  
**Project:** HyperStreamDB - Serverless Index-Streaming Data Lake

This masterclass takes you from zero to a production-grade RAG pipeline, demonstrating hardware acceleration, hybrid search, and serverless table management.

## 1. Setup & Environment

We initialize our environment and ensure all vector search dependencies are loaded.

In [1]:
import hyperstreamdb as hdb
import pyarrow as pa
import pandas as pd
import numpy as np
import os, shutil, requests, time, warnings
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

warnings.filterwarnings('ignore')
pd.set_option('display.max_colwidth', 150)

print("Environment ready.")

Environment ready.

## 2. Hardware Acceleration

HyperStreamDB can utilize Intel GPUs for massively parallel index construction. We check for available hardware here.

GPU support for Nvidia, Intel, Apple MPS, AMD(ROCm - untested)

In [2]:
import torch
device = "cpu"
if torch.cuda.is_available():
    device = "cuda:0"
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = "mps"

print(f"Using device: {device}")
ctx = hdb.Device(device)

Using device: mps

## 3. Data Preparation (AG News)

We load the AG News dataset and generate semantic embeddings using a 384-dimensional SBERT model.

In [3]:
print("Loading dataset...")
dataset = load_dataset("ag_news", split="test[:500]")
df = pd.DataFrame(dataset)
label_map = {0: "World", 1: "Sports", 2: "Business", 3: "Sci/Tech"}
df["category"] = df["label"].map(label_map)

print("Generating embeddings...")
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(df["text"].tolist())
df["embedding"] = [list(e) for e in embeddings]
print(f"Prepared {len(df)} records with {len(df['embedding'][0])}D vectors.")

df["id"] = range(len(df))

Loading dataset...
Generating embeddings...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Prepared 500 records with 384D vectors.

## 4. Table Creation (Serverless Iceberg)

HyperStreamDB tables are serverless and use standard Iceberg/Parquet formats with sidecar indices.

In [4]:
TABLE_URI = "file:///tmp/hdb_masterclass"
if os.path.exists("/tmp/hdb_masterclass"): shutil.rmtree("/tmp/hdb_masterclass")

schema = pa.schema([
    ('id', pa.int32()), 
    ('category', pa.string()),
    ('text', pa.string()),
    ('embedding', pa.list_(pa.float32(), 384))
])

table = hdb.Table.create(TABLE_URI, schema, device=ctx)
print(f"Table created at {TABLE_URI}")

Table created at file:///tmp/hdb_masterclassCommitted Manifest v1 (Schema Update)

DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)

## 5. Ingestion & Indexing

We write the data and building HNSW vector indices and Inverted scalar indices simultaneously.

In [5]:
table.add_index_columns(["embedding", "category", "text"])
table.write(df[["id", "category", "text", "embedding"]])
table.commit()
print("Data ingested and indexed successfully.")

Optimizing data layout: Shuffling rows by vector similarity (LanceDB-style)...
Written data to /tmp/hdb_masterclass/seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.parquet (500 rows)
Building indexes for batch of 500 rows
Indexing Int32 column: id
Indexing String column: text
Indexing String column: category
  Found 4 unique values
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
  Found 500 unique values
String Inverted Index written to /tmp/hdb_masterclass/seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.category.inv.parquet
Building HNSW-IVF index (blocking): 500 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 500 vectors, 4 clusters, 384 dims, M=16, use_pq=false
String Inverted Index written to /tmp/hdb_masterclass/seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.text.inv.parquet
Committed Manifest: _manifest/v2.json
  - K-Means took: 4.09ms (5 iterations, 4 clusters)
  - Grouping vectors took: 324.38µs
  - Building HNSW graphs took: 7.93ms (4 clusters)
HNSW-IVF index built in 12.36ms: 4 non-empty clusters
Committed Manifest: _manifest/v3.json
Data ingested and indexed successfully.

DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: to_manifest_entry: segment_id=seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab, generated index_files=[IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.embedding.cluster_2.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.parquet, found index_files=[IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.embedding.cluster_2.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Found version 2 on disk at Path { raw: "_manifest/v2.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v2 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.parquet

## 6. Hybrid Search Performance

We perform a semantic search combined with a scalar filter to find 'Space' news in the 'Sci/Tech' category.

In [6]:
query_vec = list(model.encode("Latest milestones in space exploration"))

results = (table.filter("category = 'Sci/Tech'")
                 .vector_search(query_vec, k=3)
                 .to_pandas())

print("Hybrid Search Results (Sci/Tech + Vector):")
display(results[["category", "text", "distance"]])

Hybrid Search Results (Sci/Tech + Vector):

DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: Total entries to prune: 1
DEBUG: Entry seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.embedding.cluster_2.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Searching for index for column: category. Available index files: [IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.embedding.cluster_2.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]

,category,text,distance
0,Sci/Tech,"The Race is On: Second Private Team Sets Launch Date for Human Spaceflight (SPACE.com) SPACE.com - TORONTO, Canada -- A second\team of rocketeers ...",1.113737
1,Sci/Tech,Stunt pilots to snag a falling NASA craft NASA #39;s three-year effort to bring some genuine star dust back to Earth is set for a dramatic finale ...,1.254462
2,Sci/Tech,Mars Rovers Relay Images Through Mars Express European Space Agency -- ESAs Mars Express has relayed pictures from one of NASA's Mars rovers for t...,1.255060

## 7. SQL & pgvector Interface

HyperStreamDB supports standard SQL with pgvector-compatible operators for vector distance.

In [7]:
session = hdb.Session()
session.register("news", table)

query_vec_str = str(query_vec).replace(' ', '')
sql_df = session.sql(f"""
    SELECT category, text, 
           embedding <-> '{query_vec_str}'::vector AS dist
    FROM news
    WHERE category = 'Sci/Tech'
    ORDER BY dist ASC LIMIT 3
""")
display(sql_df.to_pandas())

DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: Searching for index for column: category. Available index files: [IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.embedding.cluster_2.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]

,category,text,dist
0,Sci/Tech,"The Race is On: Second Private Team Sets Launch Date for Human Spaceflight (SPACE.com) SPACE.com - TORONTO, Canada -- A second\team of rocketeers ...",1.055338
1,Sci/Tech,Stunt pilots to snag a falling NASA craft NASA #39;s three-year effort to bring some genuine star dust back to Earth is set for a dramatic finale ...,1.120027
2,Sci/Tech,Mars Rovers Relay Images Through Mars Express European Space Agency -- ESAs Mars Express has relayed pictures from one of NASA's Mars rovers for t...,1.120294

## 8. Vector Aggregations

Calculate semantic centroids for entire categories directly in SQL.

In [8]:
agg_df = session.sql("""
    SELECT category, 
           vector_avg(embedding) AS centroid,
           COUNT(*) as count
    FROM news
    GROUP BY category
    order by count asc
""").to_pandas()
display(agg_df[["category", "count"]])

DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)

   category  count
0  Business    106
1     World    122
2  Sci/Tech    127
3    Sports    145

## 9. Table Maintenance

Keep the data lake healthy by compacting small files and vacuuming history.

In [9]:
print(f"Files before: {len(table.manifest().entries)}")
table.compact()
table.commit()
print(f"Files after: {len(table.manifest().entries)}")

table.vacuum(retention_versions=1)
print("Vacuum complete.")

Files before: 0
Starting compaction with strategy: binpack
Files after: 0
Found candidate: seg_dd564b4a-531b-40fa-8ec0-b804d85c90ab.parquet (1194034 bytes)
Plan: Identified 1 bins to compact.
Executing with parallelism: 4
Written data to /var/folders/96/k023nzcn1nzc1dklrz5_k1t80000gn/T/hyperstream_compact_99d89eb6-40e9-4c87-b12b-40c46cbfb9b8/compacted_20260404210904_99d89eb6-40e9-4c87-b12b-40c46cbfb9b8.parquet (500 rows)
Compacted bin 1 -> compacted_20260404210904_99d89eb6-40e9-4c87-b12b-40c46cbfb9b8.parquet
Committing Batch: +1 entries, -1 paths
Committed Manifest: _manifest/v4.json
Vacuum complete.

DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 3 on disk at Path { raw: "_manifest/v3.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v3 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 4 on disk at Path { raw: "_manifest/v4.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v4 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 4 on disk at Path { raw: "_manifest/v4.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v4 (entries=0)

## 10. Advanced Partitioning

Scale to massive datasets using identity partitioning on the category field.

In [10]:
PART_URI = "file:///tmp/part_demo"
if os.path.exists("/tmp/part_demo"): shutil.rmtree("/tmp/part_demo")

partition_spec = {
    "fields": [{"name": "category", "transform": "identity", "source_id": 1, "field_id": 1000}]
}

part_table = hdb.Table.create_partitioned(PART_URI, schema, partition_spec)
part_table.write(df[:100])
part_table.commit()

print("Partitioned physical layout:")
for entry in part_table.manifest().entries:
    print(f" - {entry.file_path.split('/')[-2:]}")

DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: to_manifest_entry: segment_id=seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617, generated index_files=[IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.parquet, found index_files=[IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_68772b63-80fd-4389-8c2a-121d24a17ae2, generated index_files=[IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_68772b63-80fd-4389-8c2a-121d24a17ae2.parquet, found index_files=[IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_68772b63-80fd-4389-8c2a-121d24a17ae2.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44, generated index_files=[IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.parquet, found index_files=[IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: to_manifest_entry: segment_id=seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945, generated index_files=[IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: to_manifest_entry: segment_id=seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe, generated index_files=[IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.parquet, found index_files=[IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: Background indexing task: segment=seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.parquet, found index_files=[IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6, generated index_files=[IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.parquet, found index_files=[IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: to_manifest_entry: segment_id=seg_e3008dae-895e-4d9c-8680-c803ee134468, generated index_files=[IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_e3008dae-895e-4d9c-8680-c803ee134468.parquet, found index_files=[IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e3008dae-895e-4d9c-8680-c803ee134468.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_85616f50-cf51-4420-8477-ff4cd4f77cd4, generated index_files=[IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: Background indexing task: segment=seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.parquet, found index_files=[IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_64e80478-059e-4177-8ebd-fc49894e5c13, generated index_files=[IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_64e80478-059e-4177-8ebd-fc49894e5c13.parquet, found index_files=[IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_64e80478-059e-4177-8ebd-fc49894e5c13.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v1 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 1 on disk at Path { raw: "_manifest/v1.json" }
DEBUG: to_manifest_entry: segment_id=seg_39b37bcd-f5aa-4d59-b324-a0f936b38077, generated index_files=[IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.parquet, found index_files=[IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d, generated index_files=[IndexFile { file_path: "seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]

DEBUG: Rust Table created with runtime: true
Optimizing data layout: Shuffling rows by vector similarity (LanceDB-style)...
Written data to /tmp/part_demo/seg_0b9d4370-292e-4f0d-b7f1-21832b0de151.parquet (1 rows)
Written data to /tmp/part_demo/seg_b3baed84-6ab8-46e3-9211-d38e4ae701ce.parquet (1 rows)
Written data to /tmp/part_demo/seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.parquet (1 rows)
Written data to /tmp/part_demo/seg_be795f7e-0638-49c7-8f1e-761f3543989d.parquet (1 rows)
Written data to /tmp/part_demo/seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.parquet (1 rows)
Written data to /tmp/part_demo/seg_c6f805ad-490d-468c-b2d6-e1ae304ba889.parquet (1 rows)
Written data to /tmp/part_demo/seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.parquet (1 rows)
Written data to /tmp/part_demo/seg_71d85573-5ec8-4c15-a4c9-1ef5b18aa975.parquet (1 rows)
Written data to /tmp/part_demo/seg_5b535e5d-deaa-47e6-89e6-ce3114a43887.parquet (1 rows)
Written data to /tmp/part_demo/seg_68772b63-80fd-4389-8c2a-121d24a17ae2.parquet (1 rows)
Written data to /tmp/part_demo/seg_74852e92-be42-496f-aed5-a71d7b754edb.parquet (1 rows)
Written data to /tmp/part_demo/seg_677b6b45-e9d2-4678-95a4-52f010fc2642.parquet (1 rows)
Written data to /tmp/part_demo/seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.parquet (1 rows)
Written data to /tmp/part_demo/seg_33a2a17e-0fa3-4e2a-b9c6-17944755a0ec.parquet (1 rows)
Written data to /tmp/part_demo/seg_f8a70501-d89d-40af-a1e4-3fbde3ba749a.parquet (1 rows)
Written data to /tmp/part_demo/seg_4e0725c8-53f9-4457-9a18-51868bec7947.parquet (1 rows)
Written data to /tmp/part_demo/seg_928e6326-5b31-4c5b-97cf-615acfa98237.parquet (1 rows)
Written data to /tmp/part_demo/seg_340cc719-bffa-4fe4-b1da-96bd73d81538.parquet (1 rows)
Written data to /tmp/part_demo/seg_209f814d-ee99-4a4b-a9e8-0247bc7e21a0.parquet (1 rows)
Written data to /tmp/part_demo/seg_deec73e1-dc76-4c16-acbe-96da09f11578.parquet (1 rows)
Written data to /tmp/part_demo/seg_67b40b32-7a01-4d98-b66c-601c2cff76a3.parquet (1 rows)
Written data to /tmp/part_demo/seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.parquet (1 rows)
Written data to /tmp/part_demo/seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.parquet (1 rows)
Written data to /tmp/part_demo/seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.parquet (1 rows)
Written data to /tmp/part_demo/seg_7fa309ff-ea6d-4f8c-add7-4dfaed99b01f.parquet (1 rows)
Written data to /tmp/part_demo/seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.parquet (1 rows)
Written data to /tmp/part_demo/seg_952265a5-3a72-4209-b6ca-9f613d40c49c.parquet (1 rows)
Written data to /tmp/part_demo/seg_1e1b8751-0576-411d-9c8a-007d9154acbb.parquet (1 rows)
Written data to /tmp/part_demo/seg_69f9e6ff-6a0e-4791-9f55-83082bf2f440.parquet (1 rows)
Written data to /tmp/part_demo/seg_4a2baeff-d2c5-4d9d-822d-66a938a57069.parquet (1 rows)
Written data to /tmp/part_demo/seg_fe9b04a7-6c18-4b65-abbb-203e69c5af73.parquet (1 rows)
Written data to /tmp/part_demo/seg_469b94dd-8d59-45f9-a848-1b99c59dbce2.parquet (1 rows)
Written data to /tmp/part_demo/seg_48f4cd2c-15eb-46e1-85f7-a7acb8e71f23.parquet (1 rows)
Written data to /tmp/part_demo/seg_6180a8c4-7c12-43f7-a795-39bd796a882b.parquet (1 rows)
Written data to /tmp/part_demo/seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.parquet (1 rows)
Written data to /tmp/part_demo/seg_78eac92c-5077-4171-872e-e1c5998f607c.parquet (1 rows)
Written data to /tmp/part_demo/seg_9dee3e60-5257-4323-bd3e-851a25f94beb.parquet (1 rows)
Written data to /tmp/part_demo/seg_3491db23-2364-407a-be0e-1a97a3d216df.parquet (1 rows)
Written data to /tmp/part_demo/seg_30605af0-5dc4-4436-9468-00b3766eb01a.parquet (1 rows)
Written data to /tmp/part_demo/seg_5ce6dfa2-2b3e-41f7-80a1-07cecd76a9f8.parquet (1 rows)
Written data to /tmp/part_demo/seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.parquet (1 rows)
Written data to /tmp/part_demo/seg_a7f78f5c-9ffb-462c-abf9-bc909395532f.parquet (1 rows)
Written data to /tmp/part_demo/seg_e521bc2f-b734-4f5e-bdb0-fee6e71b1207.parquet (1 rows)
Written data to /tmp/part_demo/seg_5d8839c7-eca5-4e8e-95de-1fa246cb2425.parquet (1 rows)
Written data to /tmp/part_demo/seg_cadabba3-4991-4852-bf33-d571c80c8302.parquet (1 rows)
Written data to /tmp/part_demo/seg_7ef1fe87-dbfa-406d-96c1-f15df1edb173.parquet (1 rows)
Written data to /tmp/part_demo/seg_e3008dae-895e-4d9c-8680-c803ee134468.parquet (1 rows)
Written data to /tmp/part_demo/seg_3e85e901-63b5-42f5-9de0-319db8e9004b.parquet (1 rows)
Written data to /tmp/part_demo/seg_64e80478-059e-4177-8ebd-fc49894e5c13.parquet (1 rows)
Written data to /tmp/part_demo/seg_eada14ed-e53c-4623-b435-702eb6f1a486.parquet (1 rows)
Written data to /tmp/part_demo/seg_7b222f65-8505-4d51-989b-cfedca80d719.parquet (1 rows)
Written data to /tmp/part_demo/seg_85bcb0ce-7572-4696-8946-2e2f9dfa69fd.parquet (1 rows)
Written data to /tmp/part_demo/seg_8754d188-c8a0-4033-9c85-a9efb430a6b8.parquet (1 rows)
Written data to /tmp/part_demo/seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.parquet (1 rows)
Written data to /tmp/part_demo/seg_3f7ac941-4cc0-4f82-9219-ab7b3b70cec3.parquet (1 rows)
Written data to /tmp/part_demo/seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f.parquet (1 rows)
Written data to /tmp/part_demo/seg_86ddcef8-d159-4c11-bc45-d9c763b89a18.parquet (1 rows)
Written data to /tmp/part_demo/seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d.parquet (1 rows)
Written data to /tmp/part_demo/seg_b3e8ce93-2142-422b-8fad-4f0773c072b6.parquet (1 rows)
Written data to /tmp/part_demo/seg_7b19a052-5161-4a8f-9144-f7901bfcc843.parquet (1 rows)
Written data to /tmp/part_demo/seg_35aefa53-980c-46c8-8929-c21e7c4c0d6c.parquet (1 rows)
Written data to /tmp/part_demo/seg_b1006a52-22f2-4c1a-ab62-4ef94d8b6c48.parquet (1 rows)
Written data to /tmp/part_demo/seg_dd1ca61e-2ca5-41f6-8bd2-a18bed1dd239.parquet (1 rows)
Written data to /tmp/part_demo/seg_e8115ecf-9e27-4595-a510-744981e404d1.parquet (1 rows)
Written data to /tmp/part_demo/seg_467b1929-5143-4441-8c61-281e3a7afd65.parquet (1 rows)
Written data to /tmp/part_demo/seg_9bb3955a-8864-4fee-85a2-3ba8964a2c16.parquet (1 rows)
Written data to /tmp/part_demo/seg_46ff729b-2b98-44ff-83bb-f33716d7101f.parquet (1 rows)
Written data to /tmp/part_demo/seg_50a2b4e1-6ab7-4951-ada8-7899f740f2e9.parquet (1 rows)
Written data to /tmp/part_demo/seg_4901ec57-0c55-4bc9-b324-456023ddfa09.parquet (1 rows)
Written data to /tmp/part_demo/seg_8b9019ec-8c4f-420b-9985-0bdde948a43b.parquet (1 rows)
Written data to /tmp/part_demo/seg_1ff75737-39bb-400c-bd70-30efefd87f69.parquet (1 rows)
Written data to /tmp/part_demo/seg_d78edf06-17bb-4878-8fd4-e0f1133f3fda.parquet (1 rows)
Written data to /tmp/part_demo/seg_aa9caf49-0435-4b66-82aa-8c80d4b63b0d.parquet (1 rows)
Written data to /tmp/part_demo/seg_3b67afc5-53e9-47cc-85f6-3f3e6dac87ab.parquet (1 rows)
Written data to /tmp/part_demo/seg_58a760c5-e154-4052-85cc-0255a8011055.parquet (1 rows)
Written data to /tmp/part_demo/seg_6d4899fd-81bd-4ffa-be0a-104121f8dfa1.parquet (1 rows)
Written data to /tmp/part_demo/seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e.parquet (1 rows)
Written data to /tmp/part_demo/seg_4deb3b6c-afb0-440b-939d-7bf881b3e67f.parquet (1 rows)
Written data to /tmp/part_demo/seg_1a2d3f45-6f24-4d69-9ba6-1df7acfaa42f.parquet (1 rows)
Written data to /tmp/part_demo/seg_54fb2753-7ca8-449c-8d39-50af71bf026d.parquet (1 rows)
Written data to /tmp/part_demo/seg_de58e263-71ce-4bce-88c7-8d022d526858.parquet (1 rows)
Written data to /tmp/part_demo/seg_f00c3d08-7de9-451e-ba09-e17df5873581.parquet (1 rows)
Written data to /tmp/part_demo/seg_d547253b-7576-4595-ac49-e4ed4027ed90.parquet (1 rows)
Written data to /tmp/part_demo/seg_7dad50b2-7578-4937-a581-5dcf47d0b136.parquet (1 rows)
Written data to /tmp/part_demo/seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b.parquet (1 rows)
Written data to /tmp/part_demo/seg_be93ea0f-3a8a-47d1-9245-938671c35e18.parquet (1 rows)
Written data to /tmp/part_demo/seg_5d659aa6-409c-414d-bae8-926ee22e5f5a.parquet (1 rows)
Written data to /tmp/part_demo/seg_3c2373f1-c507-4082-8a76-f7d5d7946b62.parquet (1 rows)
Written data to /tmp/part_demo/seg_a40cc292-7e9b-4fa8-802f-8d572f3cadc4.parquet (1 rows)
Written data to /tmp/part_demo/seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0.parquet (1 rows)
Written data to /tmp/part_demo/seg_e1fe8f5c-7825-4af1-8769-9a13f89b0849.parquet (1 rows)
Written data to /tmp/part_demo/seg_7c64db85-6ef7-4370-b82e-c30eb530203e.parquet (1 rows)
Written data to /tmp/part_demo/seg_eceb824d-2037-4002-be98-d53c292469a5.parquet (1 rows)
Written data to /tmp/part_demo/seg_bd41bc7f-f842-4de5-a052-39e2062be131.parquet (1 rows)
Written data to /tmp/part_demo/seg_4f592389-4612-489e-a41b-edf7d447125a.parquet (1 rows)
Written data to /tmp/part_demo/seg_e02d0f70-2632-4e8f-9ad9-c7afd8eb7081.parquet (1 rows)
Written data to /tmp/part_demo/seg_04ad9883-2a76-49da-bca3-7e64ed296fa8.parquet (1 rows)
Written data to /tmp/part_demo/seg_7be6f056-a93c-44dc-9ae8-652ae8525a46.parquet (1 rows)
Written data to /tmp/part_demo/seg_09cc7812-35e6-4889-a987-1ce016ce52f3.parquet (1 rows)
Written data to /tmp/part_demo/seg_95b30ab2-6b8f-40ae-9989-b09be309d79d.parquet (1 rows)
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Indexing Int32 column: id
Indexing String column: text
  Found 1 unique values
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
Indexing String column: category
  Found 1 unique values
Indexing Int32 column: id
Indexing String column: text
  Found 1 unique values
  [K-Means] Converged early at iteration 2
  - K-Means took: 154.92µs (5 iterations, 1 clusters)
  - Grouping vectors took: 2.92µs
  - Building HNSW graphs took: 17.38µs (1 clusters)
HNSW-IVF index built in 180.13µs: 1 non-empty clusters
Indexing Int32 column: id
Indexing String column: category
  Found 1 unique values
Indexing String column: text
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_0b9d4370-292e-4f0d-b7f1-21832b0de151.text.inv.parquet
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
Indexing Int32 column: id
  [K-Means] Converged early at iteration 2
Indexing String column: category
  - K-Means took: 56.42µs (5 iterations, 1 clusters)
  Found 1 unique values
  - Grouping vectors took: 1.04µs
  - Building HNSW graphs took: 11.96µs (1 clusters)
HNSW-IVF index built in 91.50µs: 1 non-empty clusters
Indexing String column: category
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
  Found 1 unique values
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 14.17µs (5 iterations, 1 clusters)
  - Grouping vectors took: 1.21µs
String Inverted Index written to /tmp/part_demo/seg_0b9d4370-292e-4f0d-b7f1-21832b0de151.category.inv.parquet
  - Building HNSW graphs took: 6.00µs (1 clusters)
HNSW-IVF index built in 24.54µs: 1 non-empty clusters
Indexing Int32 column: id
Indexing String column: text
  Found 1 unique values
Indexing String column: category
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.text.inv.parquet
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 10.00µs (5 iterations, 1 clusters)
  - Grouping vectors took: 958.00ns
  - Building HNSW graphs took: 5.50µs (1 clusters)
HNSW-IVF index built in 18.71µs: 1 non-empty clusters
Indexing String column: text
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_be795f7e-0638-49c7-8f1e-761f3543989d.text.inv.parquet
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
String Inverted Index written to /tmp/part_demo/seg_be795f7e-0638-49c7-8f1e-761f3543989d.category.inv.parquet
  [K-Means] Converged early at iteration 2
  - K-Means took: 8.88µs (5 iterations, 1 clusters)
  - Grouping vectors took: 916.00ns
  - Building HNSW graphs took: 4.50µs (1 clusters)
HNSW-IVF index built in 16.71µs: 1 non-empty clusters
Building indexes for batch of 1 rows
String Inverted Index written to /tmp/part_demo/seg_c6f805ad-490d-468c-b2d6-e1ae304ba889.category.inv.parquet
String Inverted Index written to /tmp/part_demo/seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.category.inv.parquet
Indexing String column: category
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_c6f805ad-490d-468c-b2d6-e1ae304ba889.text.inv.parquet
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
String Inverted Index written to /tmp/part_demo/seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.text.inv.parquet
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
Indexing Int32 column: id
Indexing String column: text
  [K-Means] Converged early at iteration 2
  Found 1 unique values
  - K-Means took: 11.21µs (5 iterations, 1 clusters)
  - Grouping vectors took: 917.00ns
  - Building HNSW graphs took: 5.50µs (1 clusters)
HNSW-IVF index built in 25.04µs: 1 non-empty clusters
String Inverted Index written to /tmp/part_demo/seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.category.inv.parquet
Indexing Int32 column: id
Indexing Int32 column: id
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 8.79µs (5 iterations, 1 clusters)
  - Grouping vectors took: 500.00ns
Indexing String column: category
  Found 1 unique values
Indexing String column: category
  Found 1 unique values
  - Building HNSW graphs took: 312.50µs (1 clusters)
HNSW-IVF index built in 324.67µs: 1 non-empty clusters
Building indexes for batch of 1 rows
Indexing String column: text
Indexing String column: text
  Found 1 unique values
  Found 1 unique values
Building indexes for batch of 1 rows
String Inverted Index written to /tmp/part_demo/seg_5b535e5d-deaa-47e6-89e6-ce3114a43887.text.inv.parquet
Building indexes for batch of 1 rows
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
Indexing String column: text
  Found 1 unique values
  [K-Means] Converged early at iteration 2
  - K-Means took: 9.71µs (5 iterations, 1 clusters)
  - Grouping vectors took: 833.00ns
  - Building HNSW graphs took: 4.25µs (1 clusters)
HNSW-IVF index built in 17.38µs: 1 non-empty clusters
Building indexes for batch of 1 rows
Indexing Int32 column: id
String Inverted Index written to /tmp/part_demo/seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.category.inv.parquet
Building indexes for batch of 1 rows
String Inverted Index written to /tmp/part_demo/seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.text.inv.parquet
Building indexes for batch of 1 rows
Indexing Int32 column: id
Building indexes for batch of 1 rows
Indexing String column: category
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_68772b63-80fd-4389-8c2a-121d24a17ae2.text.inv.parquet
String Inverted Index written to /tmp/part_demo/seg_5b535e5d-deaa-47e6-89e6-ce3114a43887.category.inv.parquet
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 4.17µs (5 iterations, 1 clusters)
  - Grouping vectors took: 459.00ns
  - Building HNSW graphs took: 6.42µs (1 clusters)
HNSW-IVF index built in 13.00µs: 1 non-empty clusters
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 8.50µs (5 iterations, 1 clusters)
  - Grouping vectors took: 666.00ns
  - Building HNSW graphs took: 3.83µs (1 clusters)
HNSW-IVF index built in 15.17µs: 1 non-empty clusters
String Inverted Index written to /tmp/part_demo/seg_74852e92-be42-496f-aed5-a71d7b754edb.category.inv.parquet
Indexing String column: text
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_68772b63-80fd-4389-8c2a-121d24a17ae2.category.inv.parquet
Indexing String column: text
  Found 1 unique values
Indexing String column: category
  Found 1 unique values
String Inverted Index written to /tmp/part_demo/seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.text.inv.parquet
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 7.58µs (5 iterations, 1 clusters)
  - Grouping vectors took: 875.00ns
  - Building HNSW graphs took: 4.29µs (1 clusters)
HNSW-IVF index built in 15.25µs: 1 non-empty clusters
Indexing Int32 column: id
Indexing String column: category
  Found 1 unique values
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Building indexes for batch of 1 rows
Indexing Int32 column: id
String Inverted Index written to /tmp/part_demo/seg_677b6b45-e9d2-4678-95a4-52f010fc2642.category.inv.parquet
Indexing String column: text
  Found 1 unique values
Building indexes for batch of 1 rows
String Inverted Index written to /tmp/part_demo/seg_677b6b45-e9d2-4678-95a4-52f010fc2642.text.inv.parquet
String Inverted Index written to /tmp/part_demo/seg_33a2a17e-0fa3-4e2a-b9c6-17944755a0ec.text.inv.parquet
Building indexes for batch of 1 rows
Indexing Vector column: embedding (type=FixedSizeList(Field { data_type: Float32, nullable: true }, 384))
Building HNSW-IVF index (blocking): 1 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 1 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 5.13µs (5 iterations, 1 clusters)
  - Grouping vectors took: 417.00ns
  - Building HNSW graphs took: 4.92µs (1 clusters)
HNSW-IVF index built in 11.96µs: 1 non-empty clusters
Indexing Int32 column: id
String Inverted Index written to /tmp/part_demo/seg_74852e92-be42-496f-aed5-a71d7b754edb.text.inv.parquet
Indexing String column: text
  Found 1 unique values
Indexing String column: category
  Found 1 unique values

DEBUG: to_manifest_entry: segment_id=seg_7c64db85-6ef7-4370-b82e-c30eb530203e, generated index_files=[IndexFile { file_path: "seg_7c64db85-6ef7-4370-b82e-c30eb530203e.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c64db85-6ef7-4370-b82e-c30eb530203e.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c64db85-6ef7-4370-b82e-c30eb530203e.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c64db85-6ef7-4370-b82e-c30eb530203e.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.parquet, found index_files=[IndexFile { file_path: "seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b, generated index_files=[IndexFile { file_path: "seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f, generated index_files=[IndexFile { file_path: "seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_d547253b-7576-4595-ac49-e4ed4027ed90, generated index_files=[IndexFile { file_path: "seg_d547253b-7576-4595-ac49-e4ed4027ed90.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d547253b-7576-4595-ac49-e4ed4027ed90.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d547253b-7576-4595-ac49-e4ed4027ed90.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d547253b-7576-4595-ac49-e4ed4027ed90.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.parquet, found index_files=[IndexFile { file_path: "seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_58a760c5-e154-4052-85cc-0255a8011055, generated index_files=[IndexFile { file_path: "seg_58a760c5-e154-4052-85cc-0255a8011055.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_58a760c5-e154-4052-85cc-0255a8011055.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_58a760c5-e154-4052-85cc-0255a8011055.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_58a760c5-e154-4052-85cc-0255a8011055.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_bd41bc7f-f842-4de5-a052-39e2062be131, generated index_files=[IndexFile { file_path: "seg_bd41bc7f-f842-4de5-a052-39e2062be131.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_bd41bc7f-f842-4de5-a052-39e2062be131.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_bd41bc7f-f842-4de5-a052-39e2062be131.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_bd41bc7f-f842-4de5-a052-39e2062be131.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0, generated index_files=[IndexFile { file_path: "seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_f00c3d08-7de9-451e-ba09-e17df5873581, generated index_files=[IndexFile { file_path: "seg_f00c3d08-7de9-451e-ba09-e17df5873581.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_f00c3d08-7de9-451e-ba09-e17df5873581.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_f00c3d08-7de9-451e-ba09-e17df5873581.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_f00c3d08-7de9-451e-ba09-e17df5873581.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e, generated index_files=[IndexFile { file_path: "seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_67b40b32-7a01-4d98-b66c-601c2cff76a3, generated index_files=[IndexFile { file_path: "seg_67b40b32-7a01-4d98-b66c-601c2cff76a3.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_67b40b32-7a01-4d98-b66c-601c2cff76a3.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_67b40b32-7a01-4d98-b66c-601c2cff76a3.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_67b40b32-7a01-4d98-b66c-601c2cff76a3.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_74852e92-be42-496f-aed5-a71d7b754edb, generated index_files=[IndexFile { file_path: "seg_74852e92-be42-496f-aed5-a71d7b754edb.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_74852e92-be42-496f-aed5-a71d7b754edb.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_74852e92-be42-496f-aed5-a71d7b754edb.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_74852e92-be42-496f-aed5-a71d7b754edb.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_a7f78f5c-9ffb-462c-abf9-bc909395532f, generated index_files=[IndexFile { file_path: "seg_a7f78f5c-9ffb-462c-abf9-bc909395532f.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_a7f78f5c-9ffb-462c-abf9-bc909395532f.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_a7f78f5c-9ffb-462c-abf9-bc909395532f.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_a7f78f5c-9ffb-462c-abf9-bc909395532f.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_7dad50b2-7578-4937-a581-5dcf47d0b136.parquet, found index_files=[IndexFile { file_path: "seg_7dad50b2-7578-4937-a581-5dcf47d0b136.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7dad50b2-7578-4937-a581-5dcf47d0b136.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7dad50b2-7578-4937-a581-5dcf47d0b136.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7dad50b2-7578-4937-a581-5dcf47d0b136.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_54fb2753-7ca8-449c-8d39-50af71bf026d.parquet, found index_files=[IndexFile { file_path: "seg_54fb2753-7ca8-449c-8d39-50af71bf026d.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_54fb2753-7ca8-449c-8d39-50af71bf026d.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_54fb2753-7ca8-449c-8d39-50af71bf026d.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_54fb2753-7ca8-449c-8d39-50af71bf026d.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Successfully loaded v2 (entries=0)
DEBUG: to_manifest_entry: segment_id=seg_b3e8ce93-2142-422b-8fad-4f0773c072b6, generated index_files=[IndexFile { file_path: "seg_b3e8ce93-2142-422b-8fad-4f0773c072b6.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_b3e8ce93-2142-422b-8fad-4f0773c072b6.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_b3e8ce93-2142-422b-8fad-4f0773c072b6.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_b3e8ce93-2142-422b-8fad-4f0773c072b6.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_4901ec57-0c55-4bc9-b324-456023ddfa09, generated index_files=[IndexFile { file_path: "seg_4901ec57-0c55-4bc9-b324-456023ddfa09.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_4901ec57-0c55-4bc9-b324-456023ddfa09.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_4901ec57-0c55-4bc9-b324-456023ddfa09.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_4901ec57-0c55-4bc9-b324-456023ddfa09.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_3491db23-2364-407a-be0e-1a97a3d216df, generated index_files=[IndexFile { file_path: "seg_3491db23-2364-407a-be0e-1a97a3d216df.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_3491db23-2364-407a-be0e-1a97a3d216df.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_3491db23-2364-407a-be0e-1a97a3d216df.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_3491db23-2364-407a-be0e-1a97a3d216df.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_4e0725c8-53f9-4457-9a18-51868bec7947, generated index_files=[IndexFile { file_path: "seg_4e0725c8-53f9-4457-9a18-51868bec7947.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_4e0725c8-53f9-4457-9a18-51868bec7947.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_4e0725c8-53f9-4457-9a18-51868bec7947.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_4e0725c8-53f9-4457-9a18-51868bec7947.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_deec73e1-dc76-4c16-acbe-96da09f11578, generated index_files=[IndexFile { file_path: "seg_deec73e1-dc76-4c16-acbe-96da09f11578.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_deec73e1-dc76-4c16-acbe-96da09f11578.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_deec73e1-dc76-4c16-acbe-96da09f11578.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_deec73e1-dc76-4c16-acbe-96da09f11578.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990, generated index_files=[IndexFile { file_path: "seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476, generated index_files=[IndexFile { file_path: "seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.category.inv.parquet", index_type: "inverted", column_name: Some("category"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.text.inv.parquet", index_type: "inverted", column_name: Some("text"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.id.inv.parquet", index_type: "inverted", column_name: Some("id"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]

Committed Manifest: _manifest/v3.json
Committed Manifest: _manifest/v4.json
Committed Manifest: _manifest/v5.json
Committed Manifest: _manifest/v6.json
Committed Manifest: _manifest/v7.json
Committed Manifest: _manifest/v8.json
Committed Manifest: _manifest/v9.json

DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_33a2a17e-0fa3-4e2a-b9c6-17944755a0ec.parquet
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v7 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
Successfully attached 4 indexes to manifest for segment seg_7ef1fe87-dbfa-406d-96c1-f15df1edb173.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Found version 9 on disk at Path { raw: "_manifest/v9.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v9 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_3c2373f1-c507-4082-8a76-f7d5d7946b62.parquet
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 10 on disk at Path { raw: "_manifest/v10.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v10 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 11 on disk at Path { raw: "_manifest/v11.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v11 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 11 on disk at Path { raw: "_manifest/v11.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v11 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_7dad50b2-7578-4937-a581-5dcf47d0b136.parquet
DEBUG: ManifestManager::load_latest: Found version 12 on disk at Path { raw: "_manifest/v12.json" }
DEBUG: ManifestManager::load_latest: Found version 12 on disk at Path { raw: "_manifest/v12.json" }
DEBUG: ManifestManager::load_latest: Found version 12 on disk at Path { raw: "_manifest/v12.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v12 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v12 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v12 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 12 on disk at Path { raw: "_manifest/v12.json" }
Successfully attached 4 indexes to manifest for segment seg_be0ed42f-5b65-4746-b7fe-e1fd7d94f45e.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v12 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 12 on disk at Path { raw: "_manifest/v12.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v12 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
Successfully attached 4 indexes to manifest for segment seg_3491db23-2364-407a-be0e-1a97a3d216df.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Found version 13 on disk at Path { raw: "_manifest/v13.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v13 (entries=0)

Committed Manifest: _manifest/v10.json
Committed Manifest: _manifest/v11.json
Committed Manifest: _manifest/v12.json
Committed Manifest: _manifest/v13.json
Committed Manifest: _manifest/v14.json
Committed Manifest: _manifest/v15.json
Committed Manifest: _manifest/v16.json

DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_eada14ed-e53c-4623-b435-702eb6f1a486.parquet
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Found version 15 on disk at Path { raw: "_manifest/v15.json" }
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 15 on disk at Path { raw: "_manifest/v15.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v15 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v15 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 15 on disk at Path { raw: "_manifest/v15.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v15 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 14 on disk at Path { raw: "_manifest/v14.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v14 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 15 on disk at Path { raw: "_manifest/v15.json" }
Successfully attached 4 indexes to manifest for segment seg_ff16bd4d-7763-4de3-8dc5-18664d5f0ac6.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v15 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 16 on disk at Path { raw: "_manifest/v16.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v16 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 16 on disk at Path { raw: "_manifest/v16.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v16 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 16 on disk at Path { raw: "_manifest/v16.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v16 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_54fb2753-7ca8-449c-8d39-50af71bf026d.parquet
DEBUG: ManifestManager::load_latest: Found version 16 on disk at Path { raw: "_manifest/v16.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v16 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 16 on disk at Path { raw: "_manifest/v16.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v16 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 17 on disk at Path { raw: "_manifest/v17.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v17 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 17 on disk at Path { raw: "_manifest/v17.json" }
DEBUG: ManifestManager::load_latest: Found version 17 on disk at Path { raw: "_manifest/v17.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v17 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v17 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_a7f78f5c-9ffb-462c-abf9-bc909395532f.parquet
DEBUG: ManifestManager::load_latest: Found version 17 on disk at Path { raw: "_manifest/v17.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v17 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 17 on disk at Path { raw: "_manifest/v17.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v17 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 17 on disk at Path { raw: "_manifest/v17.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v17 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 18 on disk at Path { raw: "_manifest/v18.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v18 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 18 on disk at Path { raw: "_manifest/v18.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v18 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_50a2b4e1-6ab7-4951-ada8-7899f740f2e9.parquet
DEBUG: ManifestManager::load_latest: Found version 18 on disk at Path { raw: "_manifest/v18.json" }
DEBUG: ManifestManager::load_latest: Found version 18 on disk at Path { raw: "_manifest/v18.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v18 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v18 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 19 on disk at Path { raw: "_manifest/v19.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v19 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 19 on disk at Path { raw: "_manifest/v19.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v19 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 19 on disk at Path { raw: "_manifest/v19.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v19 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_b1006a52-22f2-4c1a-ab62-4ef94d8b6c48.parquet
DEBUG: ManifestManager::load_latest: Found version 19 on disk at Path { raw: "_manifest/v19.json" }
DEBUG: ManifestManager::load_latest: Found version 20 on disk at Path { raw: "_manifest/v20.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v19 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v20 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 20 on disk at Path { raw: "_manifest/v20.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v20 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_8b9019ec-8c4f-420b-9985-0bdde948a43b.parquet
DEBUG: ManifestManager::load_latest: Found version 21 on disk at Path { raw: "_manifest/v21.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v21 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_09cc7812-35e6-4889-a987-1ce016ce52f3.parquet
DEBUG: ManifestManager::load_latest: Found version 21 on disk at Path { raw: "_manifest/v21.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v21 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 21 on disk at Path { raw: "_manifest/v21.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v21 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 21 on disk at Path { raw: "_manifest/v21.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v21 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 21 on disk at Path { raw: "_manifest/v21.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v21 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
Successfully attached 4 indexes to manifest for segment seg_46ff729b-2b98-44ff-83bb-f33716d7101f.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 22 on disk at Path { raw: "_manifest/v22.json" }
DEBUG: ManifestManager::load_latest: Found version 23 on disk at Path { raw: "_manifest/v23.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v22 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 23 on disk at Path { raw: "_manifest/v23.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v23 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v23 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 23 on disk at Path { raw: "_manifest/v23.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v23 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 23 on disk at Path { raw: "_manifest/v23.json" }
Successfully attached 4 indexes to manifest for segment seg_e521bc2f-b734-4f5e-bdb0-fee6e71b1207.parquet
DEBUG: ManifestManager::load_latest: Found version 23 on disk at Path { raw: "_manifest/v23.json" }
DEBUG: ManifestManager::load_latest: Found version 23 on disk at Path { raw: "_manifest/v23.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v23 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v23 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v23 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 24 on disk at Path { raw: "_manifest/v24.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v24 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 24 on disk at Path { raw: "_manifest/v24.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v24 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 24 on disk at Path { raw: "_manifest/v24.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v24 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_031e7974-edb1-4ae6-9ee2-0a2abbb1a945.parquet
DEBUG: ManifestManager::load_latest: Found version 24 on disk at Path { raw: "_manifest/v24.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v24 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 24 on disk at Path { raw: "_manifest/v24.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v24 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 25 on disk at Path { raw: "_manifest/v25.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v25 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_d0b038fb-6abf-4e6b-a1ea-b6f0ee856cbe.parquet
DEBUG: ManifestManager::load_latest: Found version 26 on disk at Path { raw: "_manifest/v26.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v26 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 26 on disk at Path { raw: "_manifest/v26.json" }

Committed Manifest: _manifest/v17.json
Committed Manifest: _manifest/v18.json
Committed Manifest: _manifest/v19.json
Committed Manifest: _manifest/v20.json
Committed Manifest: _manifest/v21.json
Committed Manifest: _manifest/v22.json
Committed Manifest: _manifest/v23.json
Committed Manifest: _manifest/v24.json
Committed Manifest: _manifest/v25.json
Committed Manifest: _manifest/v26.json
Committed Manifest: _manifest/v27.json
Committed Manifest: _manifest/v28.json
Committed Manifest: _manifest/v29.json
Committed Manifest: _manifest/v30.json
Committed Manifest: _manifest/v31.json
Committed Manifest: _manifest/v32.json
Committed Manifest: _manifest/v33.json
Committed Manifest: _manifest/v34.json
Committed Manifest: _manifest/v35.json

DEBUG: ManifestManager::load_latest: Successfully loaded v26 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_0b9d4370-292e-4f0d-b7f1-21832b0de151.parquet
DEBUG: ManifestManager::load_latest: Found version 26 on disk at Path { raw: "_manifest/v26.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v26 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 26 on disk at Path { raw: "_manifest/v26.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v26 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 27 on disk at Path { raw: "_manifest/v27.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v27 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_f249cb52-626c-4b2c-9bbf-d348cc67da1d.parquet
DEBUG: ManifestManager::load_latest: Found version 28 on disk at Path { raw: "_manifest/v28.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v28 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_68772b63-80fd-4389-8c2a-121d24a17ae2.parquet
DEBUG: ManifestManager::load_latest: Found version 29 on disk at Path { raw: "_manifest/v29.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v29 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_4deb3b6c-afb0-440b-939d-7bf881b3e67f.parquet
DEBUG: ManifestManager::load_latest: Found version 30 on disk at Path { raw: "_manifest/v30.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v30 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 30 on disk at Path { raw: "_manifest/v30.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v30 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_85616f50-cf51-4420-8477-ff4cd4f77cd4.parquet
DEBUG: ManifestManager::load_latest: Found version 31 on disk at Path { raw: "_manifest/v31.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v31 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_3f7ac941-4cc0-4f82-9219-ab7b3b70cec3.parquet
DEBUG: ManifestManager::load_latest: Found version 31 on disk at Path { raw: "_manifest/v31.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v31 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 32 on disk at Path { raw: "_manifest/v32.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v32 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_a40cc292-7e9b-4fa8-802f-8d572f3cadc4.parquet
DEBUG: ManifestManager::load_latest: Found version 33 on disk at Path { raw: "_manifest/v33.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v33 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 33 on disk at Path { raw: "_manifest/v33.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v33 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_e94a7ed2-0ffd-4ddf-ab7c-fb682fd1990f.parquet
DEBUG: ManifestManager::load_latest: Found version 34 on disk at Path { raw: "_manifest/v34.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v34 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 34 on disk at Path { raw: "_manifest/v34.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v34 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 34 on disk at Path { raw: "_manifest/v34.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v34 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_1e1b8751-0576-411d-9c8a-007d9154acbb.parquet
DEBUG: ManifestManager::load_latest: Found version 34 on disk at Path { raw: "_manifest/v34.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v34 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 34 on disk at Path { raw: "_manifest/v34.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v34 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 35 on disk at Path { raw: "_manifest/v35.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v35 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_e29cba0a-c1a6-457d-aef2-3b37c8aadb44.parquet
DEBUG: ManifestManager::load_latest: Found version 35 on disk at Path { raw: "_manifest/v35.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v35 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 35 on disk at Path { raw: "_manifest/v35.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v35 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 36 on disk at Path { raw: "_manifest/v36.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v36 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_71d85573-5ec8-4c15-a4c9-1ef5b18aa975.parquet
DEBUG: ManifestManager::load_latest: Found version 36 on disk at Path { raw: "_manifest/v36.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v36 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 36 on disk at Path { raw: "_manifest/v36.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v36 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 37 on disk at Path { raw: "_manifest/v37.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v37 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_7fa309ff-ea6d-4f8c-add7-4dfaed99b01f.parquet
DEBUG: ManifestManager::load_latest: Found version 38 on disk at Path { raw: "_manifest/v38.json" }
DEBUG: ManifestManager::load_latest: Found version 38 on disk at Path { raw: "_manifest/v38.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v38 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v38 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_1a2d3f45-6f24-4d69-9ba6-1df7acfaa42f.parquet
DEBUG: ManifestManager::load_latest: Found version 39 on disk at Path { raw: "_manifest/v39.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v39 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_3b67afc5-53e9-47cc-85f6-3f3e6dac87ab.parquet
DEBUG: ManifestManager::load_latest: Found version 39 on disk at Path { raw: "_manifest/v39.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v39 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 40 on disk at Path { raw: "_manifest/v40.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v40 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_445f0b0c-b84b-40f7-a802-f6b41fc8c414.parquet
DEBUG: ManifestManager::load_latest: Found version 40 on disk at Path { raw: "_manifest/v40.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v40 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 40 on disk at Path { raw: "_manifest/v40.json" }
DEBUG: ManifestManager::load_latest: Found version 40 on disk at Path { raw: "_manifest/v40.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v40 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v40 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 41 on disk at Path { raw: "_manifest/v41.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v41 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 41 on disk at Path { raw: "_manifest/v41.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v41 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_f00c3d08-7de9-451e-ba09-e17df5873581.parquet
DEBUG: ManifestManager::load_latest: Found version 41 on disk at Path { raw: "_manifest/v41.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v41 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 42 on disk at Path { raw: "_manifest/v42.json" }
DEBUG: ManifestManager::load_latest: Found version 42 on disk at Path { raw: "_manifest/v42.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v42 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v42 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_1ff75737-39bb-400c-bd70-30efefd87f69.parquet
DEBUG: ManifestManager::load_latest: Found version 43 on disk at Path { raw: "_manifest/v43.json" }
DEBUG: ManifestManager::load_latest: Found version 43 on disk at Path { raw: "_manifest/v43.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v43 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v43 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_bd41bc7f-f842-4de5-a052-39e2062be131.parquet
DEBUG: ManifestManager::load_latest: Found version 44 on disk at Path { raw: "_manifest/v44.json" }
DEBUG: ManifestManager::load_latest: Found version 44 on disk at Path { raw: "_manifest/v44.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v44 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v44 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 44 on disk at Path { raw: "_manifest/v44.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v44 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_74852e92-be42-496f-aed5-a71d7b754edb.parquet
DEBUG: ManifestManager::load_latest: Found version 45 on disk at Path { raw: "_manifest/v45.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v45 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_928e6326-5b31-4c5b-97cf-615acfa98237.parquet
DEBUG: ManifestManager::load_latest: Found version 45 on disk at Path { raw: "_manifest/v45.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v45 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 45 on disk at Path { raw: "_manifest/v45.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v45 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 46 on disk at Path { raw: "_manifest/v46.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v46 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_48de31b0-4b2f-4cc5-b32b-a7b6fa64a990.parquet

Committed Manifest: _manifest/v36.json
Committed Manifest: _manifest/v37.json
Committed Manifest: _manifest/v38.json
Committed Manifest: _manifest/v39.json
Committed Manifest: _manifest/v40.json
Committed Manifest: _manifest/v41.json
Committed Manifest: _manifest/v42.json
Committed Manifest: _manifest/v43.json
Committed Manifest: _manifest/v44.json
Committed Manifest: _manifest/v45.json
Committed Manifest: _manifest/v46.json
Committed Manifest: _manifest/v47.json
Committed Manifest: _manifest/v48.json
Committed Manifest: _manifest/v49.json
Committed Manifest: _manifest/v50.json
Committed Manifest: _manifest/v51.json
Committed Manifest: _manifest/v52.json
Committed Manifest: _manifest/v53.json
Committed Manifest: _manifest/v54.json
Committed Manifest: _manifest/v55.json
Committed Manifest: _manifest/v56.json
Committed Manifest: _manifest/v57.json

DEBUG: ManifestManager::load_latest: Found version 47 on disk at Path { raw: "_manifest/v47.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v47 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_30605af0-5dc4-4436-9468-00b3766eb01a.parquet
DEBUG: ManifestManager::load_latest: Found version 48 on disk at Path { raw: "_manifest/v48.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v48 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 48 on disk at Path { raw: "_manifest/v48.json" }
Successfully attached 4 indexes to manifest for segment seg_7c64db85-6ef7-4370-b82e-c30eb530203e.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v48 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 49 on disk at Path { raw: "_manifest/v49.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v49 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 49 on disk at Path { raw: "_manifest/v49.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v49 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_4901ec57-0c55-4bc9-b324-456023ddfa09.parquet
DEBUG: ManifestManager::load_latest: Found version 49 on disk at Path { raw: "_manifest/v49.json" }
DEBUG: ManifestManager::load_latest: Found version 49 on disk at Path { raw: "_manifest/v49.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v49 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v49 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 50 on disk at Path { raw: "_manifest/v50.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v50 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_4f592389-4612-489e-a41b-edf7d447125a.parquet
DEBUG: ManifestManager::load_latest: Found version 50 on disk at Path { raw: "_manifest/v50.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v50 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 51 on disk at Path { raw: "_manifest/v51.json" }
DEBUG: ManifestManager::load_latest: Found version 51 on disk at Path { raw: "_manifest/v51.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v51 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v51 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_78eac92c-5077-4171-872e-e1c5998f607c.parquet
DEBUG: ManifestManager::load_latest: Found version 52 on disk at Path { raw: "_manifest/v52.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v52 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_cadabba3-4991-4852-bf33-d571c80c8302.parquet
DEBUG: ManifestManager::load_latest: Found version 53 on disk at Path { raw: "_manifest/v53.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v53 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_58a760c5-e154-4052-85cc-0255a8011055.parquet
DEBUG: ManifestManager::load_latest: Found version 54 on disk at Path { raw: "_manifest/v54.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v54 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_e47f8bbb-33c2-4795-8924-d5cd5c7d2476.parquet
DEBUG: ManifestManager::load_latest: Found version 54 on disk at Path { raw: "_manifest/v54.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v54 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 55 on disk at Path { raw: "_manifest/v55.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v55 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_7b19a052-5161-4a8f-9144-f7901bfcc843.parquet
DEBUG: ManifestManager::load_latest: Found version 55 on disk at Path { raw: "_manifest/v55.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v55 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 56 on disk at Path { raw: "_manifest/v56.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v56 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_5ce6dfa2-2b3e-41f7-80a1-07cecd76a9f8.parquet
DEBUG: ManifestManager::load_latest: Found version 57 on disk at Path { raw: "_manifest/v57.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v57 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_209f814d-ee99-4a4b-a9e8-0247bc7e21a0.parquet
DEBUG: ManifestManager::load_latest: Found version 58 on disk at Path { raw: "_manifest/v58.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v58 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_5b535e5d-deaa-47e6-89e6-ce3114a43887.parquet
DEBUG: ManifestManager::load_latest: Found version 59 on disk at Path { raw: "_manifest/v59.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v59 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 59 on disk at Path { raw: "_manifest/v59.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v59 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_b3baed84-6ab8-46e3-9211-d38e4ae701ce.parquet
DEBUG: ManifestManager::load_latest: Found version 59 on disk at Path { raw: "_manifest/v59.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v59 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 59 on disk at Path { raw: "_manifest/v59.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v59 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 60 on disk at Path { raw: "_manifest/v60.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v60 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_86ddcef8-d159-4c11-bc45-d9c763b89a18.parquet

Committed Manifest: _manifest/v58.json
Committed Manifest: _manifest/v59.json
Committed Manifest: _manifest/v60.json
Committed Manifest: _manifest/v61.json
Committed Manifest: _manifest/v62.json
Committed Manifest: _manifest/v63.json
Committed Manifest: _manifest/v64.json
Committed Manifest: _manifest/v65.json
Committed Manifest: _manifest/v66.json

DEBUG: ManifestManager::load_latest: Found version 61 on disk at Path { raw: "_manifest/v61.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v61 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_95b30ab2-6b8f-40ae-9989-b09be309d79d.parquet
DEBUG: ManifestManager::load_latest: Found version 62 on disk at Path { raw: "_manifest/v62.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v62 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 62 on disk at Path { raw: "_manifest/v62.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v62 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 62 on disk at Path { raw: "_manifest/v62.json" }
Successfully attached 4 indexes to manifest for segment seg_aa9caf49-0435-4b66-82aa-8c80d4b63b0d.parquet
DEBUG: ManifestManager::load_latest: Successfully loaded v62 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 63 on disk at Path { raw: "_manifest/v63.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v63 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_9dee3e60-5257-4323-bd3e-851a25f94beb.parquet
DEBUG: ManifestManager::load_latest: Found version 64 on disk at Path { raw: "_manifest/v64.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v64 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_7be6f056-a93c-44dc-9ae8-652ae8525a46.parquet
DEBUG: ManifestManager::load_latest: Found version 65 on disk at Path { raw: "_manifest/v65.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v65 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_39b37bcd-f5aa-4d59-b324-a0f936b38077.parquet
DEBUG: ManifestManager::load_latest: Found version 66 on disk at Path { raw: "_manifest/v66.json" }
DEBUG: ManifestManager::load_latest: Found version 66 on disk at Path { raw: "_manifest/v66.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v66 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v66 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_e1fe8f5c-7825-4af1-8769-9a13f89b0849.parquet
DEBUG: ManifestManager::load_latest: Found version 67 on disk at Path { raw: "_manifest/v67.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v67 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_8754d188-c8a0-4033-9c85-a9efb430a6b8.parquet
DEBUG: ManifestManager::load_latest: Found version 68 on disk at Path { raw: "_manifest/v68.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v68 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_3e85e901-63b5-42f5-9de0-319db8e9004b.parquet
DEBUG: ManifestManager::load_latest: Found version 69 on disk at Path { raw: "_manifest/v69.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v69 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 69 on disk at Path { raw: "_manifest/v69.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v69 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_04ad9883-2a76-49da-bca3-7e64ed296fa8.parquet
DEBUG: ManifestManager::load_latest: Found version 70 on disk at Path { raw: "_manifest/v70.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v70 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 70 on disk at Path { raw: "_manifest/v70.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v70 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_952265a5-3a72-4209-b6ca-9f613d40c49c.parquet
DEBUG: ManifestManager::load_latest: Found version 71 on disk at Path { raw: "_manifest/v71.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v71 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_deec73e1-dc76-4c16-acbe-96da09f11578.parquet
DEBUG: ManifestManager::load_latest: Found version 72 on disk at Path { raw: "_manifest/v72.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v72 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_5d659aa6-409c-414d-bae8-926ee22e5f5a.parquet
DEBUG: ManifestManager::load_latest: Found version 73 on disk at Path { raw: "_manifest/v73.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v73 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_0cc00ea0-eb9c-4b77-bf0e-96ec0182879b.parquet
DEBUG: ManifestManager::load_latest: Found version 73 on disk at Path { raw: "_manifest/v73.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v73 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 74 on disk at Path { raw: "_manifest/v74.json" }
DEBUG: ManifestManager::load_latest: Found version 74 on disk at Path { raw: "_manifest/v74.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v74 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v74 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_e02d0f70-2632-4e8f-9ad9-c7afd8eb7081.parquet
DEBUG: ManifestManager::load_latest: Found version 75 on disk at Path { raw: "_manifest/v75.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v75 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_69f9e6ff-6a0e-4791-9f55-83082bf2f440.parquet
DEBUG: ManifestManager::load_latest: Found version 75 on disk at Path { raw: "_manifest/v75.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v75 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 76 on disk at Path { raw: "_manifest/v76.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v76 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_be93ea0f-3a8a-47d1-9245-938671c35e18.parquet
DEBUG: ManifestManager::load_latest: Found version 77 on disk at Path { raw: "_manifest/v77.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v77 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_7b222f65-8505-4d51-989b-cfedca80d719.parquet
DEBUG: ManifestManager::load_latest: Found version 78 on disk at Path { raw: "_manifest/v78.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v78 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 78 on disk at Path { raw: "_manifest/v78.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v78 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_35aefa53-980c-46c8-8929-c21e7c4c0d6c.parquet
DEBUG: ManifestManager::load_latest: Found version 79 on disk at Path { raw: "_manifest/v79.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v79 (entries=0)

Committed Manifest: _manifest/v67.json
Committed Manifest: _manifest/v68.json
Committed Manifest: _manifest/v69.json
Committed Manifest: _manifest/v70.json
Committed Manifest: _manifest/v71.json
Committed Manifest: _manifest/v72.json
Committed Manifest: _manifest/v73.json
Committed Manifest: _manifest/v74.json
Committed Manifest: _manifest/v75.json
Committed Manifest: _manifest/v76.json
Committed Manifest: _manifest/v77.json
Committed Manifest: _manifest/v78.json
Committed Manifest: _manifest/v79.json
Committed Manifest: _manifest/v80.json
Committed Manifest: _manifest/v81.json
Committed Manifest: _manifest/v82.json

Successfully attached 4 indexes to manifest for segment seg_e8115ecf-9e27-4595-a510-744981e404d1.parquet
DEBUG: ManifestManager::load_latest: Found version 80 on disk at Path { raw: "_manifest/v80.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v80 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 80 on disk at Path { raw: "_manifest/v80.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v80 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_dd9bd59d-2214-45fd-9eac-8d37375b4914.parquet
DEBUG: ManifestManager::load_latest: Found version 81 on disk at Path { raw: "_manifest/v81.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v81 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_e3008dae-895e-4d9c-8680-c803ee134468.parquet
DEBUG: ManifestManager::load_latest: Found version 82 on disk at Path { raw: "_manifest/v82.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v82 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_677b6b45-e9d2-4678-95a4-52f010fc2642.parquet
DEBUG: ManifestManager::load_latest: Found version 83 on disk at Path { raw: "_manifest/v83.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v83 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_be795f7e-0638-49c7-8f1e-761f3543989d.parquet
DEBUG: ManifestManager::load_latest: Found version 83 on disk at Path { raw: "_manifest/v83.json" }
DEBUG: ManifestManager::load_latest: Found version 83 on disk at Path { raw: "_manifest/v83.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v83 (entries=0)
DEBUG: ManifestManager::load_latest: Successfully loaded v83 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 84 on disk at Path { raw: "_manifest/v84.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v84 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_fe9b04a7-6c18-4b65-abbb-203e69c5af73.parquet
DEBUG: ManifestManager::load_latest: Found version 85 on disk at Path { raw: "_manifest/v85.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v85 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_6180a8c4-7c12-43f7-a795-39bd796a882b.parquet
DEBUG: ManifestManager::load_latest: Found version 86 on disk at Path { raw: "_manifest/v86.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v86 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_d78edf06-17bb-4878-8fd4-e0f1133f3fda.parquet
DEBUG: ManifestManager::load_latest: Found version 87 on disk at Path { raw: "_manifest/v87.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v87 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_340cc719-bffa-4fe4-b1da-96bd73d81538.parquet

Committed Manifest: _manifest/v83.json
Committed Manifest: _manifest/v84.json
Committed Manifest: _manifest/v85.json
Committed Manifest: _manifest/v86.json
Committed Manifest: _manifest/v87.json
Committed Manifest: _manifest/v88.json
Committed Manifest: _manifest/v89.json
Committed Manifest: _manifest/v90.json

DEBUG: ManifestManager::load_latest: Found version 88 on disk at Path { raw: "_manifest/v88.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v88 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_4a2baeff-d2c5-4d9d-822d-66a938a57069.parquet
DEBUG: ManifestManager::load_latest: Found version 89 on disk at Path { raw: "_manifest/v89.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v89 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_48f4cd2c-15eb-46e1-85f7-a7acb8e71f23.parquet
DEBUG: ManifestManager::load_latest: Found version 90 on disk at Path { raw: "_manifest/v90.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v90 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_eceb824d-2037-4002-be98-d53c292469a5.parquet
DEBUG: ManifestManager::load_latest: Found version 91 on disk at Path { raw: "_manifest/v91.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v91 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_85bcb0ce-7572-4696-8946-2e2f9dfa69fd.parquet
DEBUG: ManifestManager::load_latest: Found version 92 on disk at Path { raw: "_manifest/v92.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v92 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_20d10b93-6efa-4bf9-829b-7b1f3ee381c0.parquet
DEBUG: ManifestManager::load_latest: Found version 93 on disk at Path { raw: "_manifest/v93.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v93 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_67b40b32-7a01-4d98-b66c-601c2cff76a3.parquet
DEBUG: ManifestManager::load_latest: Found version 93 on disk at Path { raw: "_manifest/v93.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v93 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 94 on disk at Path { raw: "_manifest/v94.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v94 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 94 on disk at Path { raw: "_manifest/v94.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v94 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_b3e8ce93-2142-422b-8fad-4f0773c072b6.parquet

Committed Manifest: _manifest/v91.json
Committed Manifest: _manifest/v92.json
Committed Manifest: _manifest/v93.json
Committed Manifest: _manifest/v94.json
Committed Manifest: _manifest/v95.json
Committed Manifest: _manifest/v96.json

DEBUG: ManifestManager::load_latest: Found version 95 on disk at Path { raw: "_manifest/v95.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v95 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_5d8839c7-eca5-4e8e-95de-1fa246cb2425.parquet
DEBUG: ManifestManager::load_latest: Found version 96 on disk at Path { raw: "_manifest/v96.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v96 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_467b1929-5143-4441-8c61-281e3a7afd65.parquet
DEBUG: ManifestManager::load_latest: Found version 97 on disk at Path { raw: "_manifest/v97.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v97 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_9bb3955a-8864-4fee-85a2-3ba8964a2c16.parquet
DEBUG: ManifestManager::load_latest: Found version 97 on disk at Path { raw: "_manifest/v97.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v97 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 98 on disk at Path { raw: "_manifest/v98.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v98 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_64e80478-059e-4177-8ebd-fc49894e5c13.parquet

Committed Manifest: _manifest/v97.json
Committed Manifest: _manifest/v98.json
Committed Manifest: _manifest/v99.json

DEBUG: ManifestManager::load_latest: Found version 99 on disk at Path { raw: "_manifest/v99.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v99 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_f8a70501-d89d-40af-a1e4-3fbde3ba749a.parquet
DEBUG: ManifestManager::load_latest: Found version 99 on disk at Path { raw: "_manifest/v99.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v99 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 100 on disk at Path { raw: "_manifest/v100.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v100 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_6d4899fd-81bd-4ffa-be0a-104121f8dfa1.parquet

Committed Manifest: _manifest/v100.json
Committed Manifest: _manifest/v101.json
Committed Manifest: _manifest/v102.json
Partitioned physical layout:

DEBUG: ManifestManager::load_latest: Found version 101 on disk at Path { raw: "_manifest/v101.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v101 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_6efbc46e-fa4d-4fef-8db0-d81a2c3f8617.parquet
DEBUG: ManifestManager::load_latest: Found version 102 on disk at Path { raw: "_manifest/v102.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v102 (entries=0)

## 11. End-to-End RAG Pipeline

Using SQuAD validation data to build a knowledge-backed Q&A system.

In [11]:
print("Loading SQuAD contexts...")
squad = load_dataset("squad", split="validation[0:100]")
squad_df = pd.DataFrame(squad).drop_duplicates(subset=["context"])

squad_emb = model.encode(squad_df["context"].tolist(), show_progress_bar=True)
squad_df["embedding"] = [list(e) for e in squad_emb]

rag_table = hdb.Table("rag_db_presentation")
rag_table.add_index_columns(["embedding", "context"])
rag_table.write(squad_df[["context", "title", "embedding"]])
rag_table.commit()
print("RAG knowledge base initialized.")

Loading SQuAD contexts...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Written data to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.parquet (4 rows)
Building indexes for batch of 4 rows
Indexing String column: context
Indexing Vector column: embedding (type=List(Field { data_type: Float32, nullable: true }))
Indexing Int64 column: __index_level_0__
  Found 4 unique values
Indexing String column: title
  Found 1 unique values
Building HNSW-IVF index (blocking): 4 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 4 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
String Inverted Index written to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.context.inv.parquet
  - K-Means took: 192.63µs (5 iterations, 1 clusters)
  - Grouping vectors took: 63.92µs
String Inverted Index written to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.title.inv.parquet
  - Building HNSW graphs took: 51.92µs (1 clusters)
HNSW-IVF index built in 315.54µs: 1 non-empty clusters
Written data to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.parquet (4 rows)
Building indexes for batch of 4 rows
Indexing String column: context
Indexing String column: title
  Found 4 unique values
  Found 1 unique values
Indexing Vector column: embedding (type=List(Field { data_type: Float32, nullable: true, metadata: {"iceberg.id": "301"} }))
Indexing Int64 column: __index_level_0__
Building HNSW-IVF index (blocking): 4 vectors, 384 dims, use_pq=false
Building HNSW-IVF index: 4 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  [K-Means] Converged early at iteration 2
  - K-Means took: 83.67µs (5 iterations, 1 clusters)
  - Grouping vectors took: 28.88µs
  - Building HNSW graphs took: 20.08µs (1 clusters)
HNSW-IVF index built in 136.79µs: 1 non-empty clusters
String Inverted Index written to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.title.inv.parquet
String Inverted Index written to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.context.inv.parquet
Written data to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_ffc57efc-6e76-4d5c-a999-8888e056639c.parquet (4 rows)
Building indexes for batch of 4 rows
Indexing String column: context
Indexing Vector column: embedding (type=List(Field { data_type: Float32, nullable: true, metadata: {"iceberg.id": "301"} }))
  Found 4 unique values
Building HNSW-IVF index (blocking): 4 vectors, 384 dims, use_pq=false
Indexing String column: title
Building HNSW-IVF index: 4 vectors, 1 clusters, 384 dims, M=16, use_pq=false
  Found 1 unique values
Indexing Int64 column: __index_level_0__
  [K-Means] Converged early at iteration 2
  - K-Means took: 96.13µs (5 iterations, 1 clusters)
  - Grouping vectors took: 53.50µs
  - Building HNSW graphs took: 122.58µs (1 clusters)
HNSW-IVF index built in 305.46µs: 1 non-empty clusters
String Inverted Index written to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_ffc57efc-6e76-4d5c-a999-8888e056639c.context.inv.parquet
String Inverted Index written to /Users/ralbright/projects/hyperstreamdb/demo/rag_db_presentation/seg_ffc57efc-6e76-4d5c-a999-8888e056639c.title.inv.parquet
Committed Manifest: _manifest/v7.json
Committed Manifest: _manifest/v8.json
RAG knowledge base initialized.

DEBUG: ManifestManager::load_latest: Found version 5 on disk at Path { raw: "_manifest/v5.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v5 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 5 on disk at Path { raw: "_manifest/v5.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v5 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 5 on disk at Path { raw: "_manifest/v5.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v5 (entries=0)
DEBUG: to_manifest_entry: segment_id=seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e, generated index_files=[IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: to_manifest_entry: segment_id=seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077, generated index_files=[IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Found version 5 on disk at Path { raw: "_manifest/v5.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v5 (entries=0)
DEBUG: ManifestManager::load_latest: Found version 6 on disk at Path { raw: "_manifest/v6.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v6 (entries=2)
DEBUG: ManifestManager::load_latest: Found version 6 on disk at Path { raw: "_manifest/v6.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v6 (entries=2)
DEBUG: ManifestManager::load_latest: Found version 6 on disk at Path { raw: "_manifest/v6.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v6 (entries=2)
DEBUG: to_manifest_entry: segment_id=seg_ffc57efc-6e76-4d5c-a999-8888e056639c, generated index_files=[IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Background indexing task: segment=seg_ffc57efc-6e76-4d5c-a999-8888e056639c.parquet, found index_files=[IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: ManifestManager::load_latest: Found version 6 on disk at Path { raw: "_manifest/v6.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v6 (entries=2)
DEBUG: ManifestManager::load_latest: Found version 7 on disk at Path { raw: "_manifest/v7.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v7 (entries=0)
Successfully attached 4 indexes to manifest for segment seg_ffc57efc-6e76-4d5c-a999-8888e056639c.parquet

## 12. Inference with Retrieval

Connect retrieval to the LLM (requires GROQ_API_KEY).

In [18]:
def ask_hdb(question):
    # Convert question to an embedding (using your local model)
    q_emb = model.encode(question)
    
    # Perform a vector search on your table
    # This is where your table data gets pulled in!
    ctx_df = rag_table.to_pandas(vector_filter={
        "column": "embedding", 
        "query": q_emb, 
        "k": 3  # Get top 3 matching contexts
    })
    
    # Combine retrieved contexts into one string
    contexts = ctx_df["context"].tolist()
    prompt = f"Answer the question based ONLY on this context:\n\n" + "\n".join(contexts) + f"\n\nQuestion: {question}"
    
    # Use a supported Groq model
    model_name = "llama-3.3-70b-versatile"
    
    api_key = os.environ.get("GROQ_TOKEN")
    r = requests.post("https://api.groq.com/openai/v1/chat/completions", 
                      headers={"Authorization": f"Bearer {api_key}"},
                      json={"model": model_name, "messages": [{"role": "user", "content": prompt}]})
    
    res = r.json()
    if "choices" not in res:
        # This will show you the exact error from Groq (e.g., "model_not_found")
        print(f"Groq API Error: {res}")
        return "Error from API"
        
    return res["choices"][0]["message"]["content"]

In [19]:

question = "Where were the first modern Olympic games?"
print(f"Q: {question}\nA: {ask_hdb(question)}")

DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: Total entries to prune: 3
DEBUG: Entry seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Entry seg_ffc57efc-6e76-4d5c-a999-8888e056639c.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Entry seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]

Q: Where were the first modern Olympic games?
A: The context provided does not mention the location of the first modern Olympic games. The information is about Super Bowl 50, its broadcast, commercial costs, halftime show, and viewership. It does not contain any details about the Olympic games.

In [20]:
question = "What city was superbowl 50 played at?"
print(f"Q: {question}\nA: {ask_hdb(question)}")

DEBUG: ManifestManager::load_latest: Found version 8 on disk at Path { raw: "_manifest/v8.json" }
DEBUG: ManifestManager::load_latest: Successfully loaded v8 (entries=0)
DEBUG: Total entries to prune: 3
DEBUG: Entry seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_d2d2d539-d05e-4976-8bcb-3a9c38113a5e.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Entry seg_ffc57efc-6e76-4d5c-a999-8888e056639c.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_ffc57efc-6e76-4d5c-a999-8888e056639c.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]
DEBUG: Entry seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.parquet: partitions={}, index_files=[IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.title.inv.parquet", index_type: "inverted", column_name: Some("title"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.context.inv.parquet", index_type: "inverted", column_name: Some("context"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.__index_level_0__.inv.parquet", index_type: "inverted", column_name: Some("__index_level_0__"), blob_type: None, offset: None, length: None }, IndexFile { file_path: "seg_7c134cc4-c2d1-48aa-8d11-5298ec6c7077.embedding.cluster_0.hnsw.graph", index_type: "vector", column_name: Some("embedding"), blob_type: None, offset: None, length: None }]

Q: What city was superbowl 50 played at?
A: The game was played at Levi's Stadium in the San Francisco Bay Area at Santa Clara, California.